Hooks:Add("LocalizationManagerPostInit", "BriefingBuildMenu_LocalizationManagerPostInit", function(localization_manager)
	localization_manager:add_localized_strings({
		bbm_button = "BUILD",
		bbm_dialog_title = "BUILD",
		bbm_dialog_text = "Choose what you want to configure.",
		bbm_skilltree = "SKILL TREE",
		bbm_weapon_modifications = "WEAPON MODIFICATIONS",
		bbm_blackmarket_title = "BLACKMARKET: $WEAPON",
		bbm_weapon_choice_description = "Choose the equipped weapon you want to modify.",
		bbm_primary_weapon = "PRIMARY WEAPON",
		bbm_secondary_weapon = "SECONDARY WEAPON",
		bbm_part_equipped = "EQUIPPED",
		bbm_part_available = "AVAILABLE",
		bbm_part_unowned = "NOT OWNED",
		bbm_part_unaffordable = "NOT ENOUGH CASH",
		bbm_part_incompatible = "INCOMPATIBLE",
		bbm_part_locked = "CATEGORY LOCKED",
		bbm_part_owned = "OWNED: $AMOUNT",
		bbm_part_price = "PRICE: $PRICE",
		bbm_weapon_stats = "WEAPON STATISTICS",
		bbm_more_weapon_stats_unavailable = "MORE WEAPON STATS IS NOT INSTALLED OR ENABLED.",
		bbm_weapon_stats_calculation_unavailable = "STATISTICS ARE NOT AVAILABLE FOR THIS MODIFICATION.",
		bbm_part_install = "[ENTER] INSTALL",
		bbm_part_remove = "[ENTER] REMOVE",
		bbm_part_no_action = "THIS MODIFICATION CANNOT BE INSTALLED",
		bbm_detection_risk = "DETECTION RISK: $RISK",
		bbm_page = "PAGE $CURRENT / $TOTAL",
		bbm_previous_page = "< PREVIOUS",
		bbm_next_page = "NEXT >",
		bbm_import_build = "IMPORT BUILD",
		bbm_export_build = "EXPORT BUILD",
		bbm_error_title = "BUILD MENU ERROR",
		bbm_open_error = "The requested screen could not be opened:\n$ERROR",
		bbm_weapon_error = "The equipped weapon could not be found for category '$ERROR'.",
		bbm_weapon_transaction_error = "The weapon modification '$ERROR' could not be applied. The current blueprint was left unchanged or rejected by the game.",
		bbm_builder_error = "PD2Builder loader could not complete the operation:\n$ERROR"
	})
end)

